author: "MCP-Search"
version: "3.9"
services:
  db:
    image: ankane/pgvector:latest           # Postgres 16 + pgvector
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mcpsearch
    ports: ["5432:5432"]
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5 